steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/bgov-web/bgov-backend', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/bgov-web/bgov-backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'bgov-backend', '--image', 'eu.gcr.io/bgov-web/bgov-backend', '--region', 'europe-west1', '--platform', 'managed']
